### ISSUE TITLE
How could you get the data from amiami.com

### ISSUE THREAD

**Issue by spacime** [CherryPerry/Amiami-kotlin-backend#1]
How could I get data from amiami.com so that I could show the data in the frontend? Should I use scrapy to get the data?

Thanks!

**Comment by CherryPerry** [comment]
Do you want to store pre-owned item's data and implement same functionality as android app? Then follow installation steps and get JSON from `/v1/data` endpoint. Or you can ignore endpoint and get actual data from `MongoDB` directly.

If you don't need to store anything or you need not only pre-owned section, just do direct requests to `amiami.com` like https://api.amiami.com/api/v1.0/item?scode=FIGURE-035995-S001&lang=eng. You can check all required requests via browser network inspector.
